---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dapr-poc
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./dapr
  prune: true
  sourceRef:
    kind: GitRepository
    name: dapr-poc
  targetNamespace: dapr-poc

