---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mcs-dapr-poc-frontend
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./mcs-dapr-poc-frontend/kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: dapr-poc
  targetNamespace: spark-namespace

